kind: Service
apiVersion: v1
metadata:
  name: connectionsposts-svc
spec:
  selector:
    app: connectionsposts
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: connectionsposts
  labels:
    app: connectionsposts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connectionsposts
  template:
    metadata:
      labels:
        app: connectionsposts
    spec:
      containers:
      - name: connectionsposts
        image: cdavisafc/cloudnative-appconfig-connectionposts:0.0.2
        env:
          - name: INSTANCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONNECTIONPOSTSCONTROLLER_POSTSURL
            value: "http://192.168.99.100:32510/posts?userIds="
          - name: CONNECTIONPOSTSCONTROLLER_CONNECTIONSURL
            value: "http://192.168.99.100:31773/connections/"
          - name: CONNECTIONPOSTSCONTROLLER_USERSURL
            value: "http://192.168.99.100:31773/users/"
          - name: REDIS_HOSTNAME
            value: "192.168.99.100"
          - name: REDIS_PORT
            value: "31537"
          - name: SPRING_APPLICATION_NAME
            value: "mycookbook"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://192.168.99.100:31868"